package main

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/polter-dev/discord_terminal_presence/internal/config"
	updatepkg "github.com/polter-dev/discord_terminal_presence/internal/update"
)

// flagIgnoringChecker reports an available update no matter what the caller
// passes for configEnabled, so tests can prove runAutomaticUpdate enforces the
// update_check opt-out itself rather than relying on Checker to do it.
type flagIgnoringChecker struct {
	mu     sync.Mutex
	latest string
	calls  int
}

func (c *flagIgnoringChecker) Refresh(_ context.Context, current string, _ bool) (updatepkg.Result, bool) {
	c.mu.Lock()
	c.calls++
	c.mu.Unlock()
	return updatepkg.Result{Current: current, Latest: c.latest, Method: updatepkg.InstallGo}, true
}

// callsSafe reads the counter under the lock, for tests that observe a
// still-running daemon loop.
func (c *flagIgnoringChecker) callsSafe() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.calls
}

// seedFailedAttempt records a failed automatic-update attempt for target and
// returns the state path holding it.
func seedFailedAttempt(t *testing.T, target string) string {
	t.Helper()
	statePath := filepath.Join(t.TempDir(), "update-check.json")
	attemptedAt := time.Date(2026, 7, 28, 17, 46, 2, 0, time.UTC)
	err := updatepkg.RecordAutomaticUpdateAttempt(statePath, target, attemptedAt, errors.New("download installer: exec failed"))
	if err != nil {
		t.Fatal(err)
	}
	// Assert the harness actually planted something: a probe that measures
	// an empty state file would "pass" for entirely the wrong reason.
	if _, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath); !ok {
		t.Fatalf("harness broken: no attempt recorded at %s", statePath)
	}
	return statePath
}

// TestAutomaticUpdateCheckClearsAttemptForTargetThatIsNotTheLatest is the
// issue #458 cause-2 regression: the recorded target "1.1.0" was never a real
// release and sorts newer than every shipped version, so the pre-existing
// clearing rule (!IsNewer(current, target)) could never fire and the record
// was immortal regardless of the auto_update gate.
func TestAutomaticUpdateCheckClearsAttemptForTargetThatIsNotTheLatest(t *testing.T) {
	for _, autoUpdate := range []bool{false, true} {
		name := "auto_update_off"
		if autoUpdate {
			name = "auto_update_on"
		}
		t.Run(name, func(t *testing.T) {
			_ = os.Unsetenv("NO_UPDATE_CHECK")
			statePath := seedFailedAttempt(t, "1.1.0")

			// A real check reports 0.1.3 as the latest release. "1.1.0" is
			// not on offer, so nothing can ever act on that record again.
			source := &staticReleaseSource{latest: "0.1.3"}
			checker := updatepkg.NewChecker(source, statePath)
			checker.DetectInstall = func() updatepkg.InstallMethod { return updatepkg.InstallGo }
			cfg := config.Default()
			cfg.AutoUpdate = autoUpdate
			runner := &recordingUpdateRunner{err: errors.New("still broken")}

			runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", checker, runner, statePath, "linux")

			attempt, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath)
			if ok && attempt.Target == "1.1.0" {
				t.Fatalf("bogus attempt for 1.1.0 survived a check that offered 0.1.3: %+v", attempt)
			}
			if autoUpdate {
				// The enabled path re-attempts and legitimately records a
				// fresh failure for the real latest; that is not the stale
				// record and must not be confused for one.
				if !ok || attempt.Target != "0.1.3" {
					t.Fatalf("attempt = (%+v, %t), want a fresh failure for 0.1.3", attempt, ok)
				}
			} else if ok {
				t.Fatalf("attempt = %+v, want cleared with auto_update off", attempt)
			}
		})
	}
}

// TestAutomaticUpdateCheckClearsRealWorldStuckRecord runs the fix against the
// exact bytes sitting in the repo owner's ~/.cache/termp/update-check.json,
// copied verbatim from issue #458 rather than regenerated by the current
// writer. A rule about what to delete has to be tested on the artifact that is
// actually on disk, not on one this build just produced.
func TestAutomaticUpdateCheckClearsRealWorldStuckRecord(t *testing.T) {
	_ = os.Unsetenv("NO_UPDATE_CHECK")
	statePath := filepath.Join(t.TempDir(), "update-check.json")
	const stuck = `{"automatic_update":{"attempted_at":"2026-07-28T17:46:02-04:00","target_version":"1.1.0",` +
		`"error":"download installer from https://raw.githubusercontent.com/polter-dev/discord_terminal_presence/1.1.0/install.sh: exec failed"}}`
	if err := os.WriteFile(statePath, []byte(stuck), 0o600); err != nil {
		t.Fatal(err)
	}
	// The record must render before the fix gets a chance to clear it,
	// otherwise this test could pass simply because nothing was ever there.
	if got := automaticUpdateFailure(statePath, "0.1.2"); got == "" {
		t.Fatal("harness broken: seeded record does not render as a failure")
	}

	source := &staticReleaseSource{latest: "0.1.3"}
	checker := updatepkg.NewChecker(source, statePath)
	checker.DetectInstall = func() updatepkg.InstallMethod { return updatepkg.InstallGo }
	cfg := config.Default()
	cfg.AutoUpdate = false

	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", checker, &recordingUpdateRunner{}, statePath, "linux")

	if got := automaticUpdateFailure(statePath, "0.1.2"); got != "" {
		t.Fatalf("status still reports the stuck record: %q", got)
	}
	// The release-check metadata written by the same check must survive the
	// clear; only the attempt is removed.
	data, err := os.ReadFile(statePath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "0.1.3") {
		t.Fatalf("cache lost its release metadata: %s", data)
	}
}

// TestAutomaticUpdateCheckPreservesAttemptForCurrentLatest is the other half
// of the rule: a failure for the version the release source is still offering
// is a real, actionable failure and `termp status` must keep showing it.
func TestAutomaticUpdateCheckPreservesAttemptForCurrentLatest(t *testing.T) {
	_ = os.Unsetenv("NO_UPDATE_CHECK")
	statePath := seedFailedAttempt(t, "v1.1.0")

	// The v-prefix mismatch is deliberate: the recorded target and the
	// checked latest are the same release, and precedence comparison (not
	// string equality) has to say so.
	source := &staticReleaseSource{latest: "1.1.0"}
	checker := updatepkg.NewChecker(source, statePath)
	checker.DetectInstall = func() updatepkg.InstallMethod { return updatepkg.InstallGo }
	cfg := config.Default()
	cfg.AutoUpdate = false
	runner := &recordingUpdateRunner{}

	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "1.0.0", checker, runner, statePath, "linux")

	attempt, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath)
	if !ok || attempt.Error == "" {
		t.Fatalf("attempt = (%+v, %t), want the still-relevant v1.1.0 failure preserved", attempt, ok)
	}
	if got := automaticUpdateFailure(statePath, "1.0.0"); got == "" {
		t.Fatal("status stopped reporting a failure that is still the latest release")
	}
}

// TestAutomaticUpdateCheckClearsStaleAttemptWithAutoUpdateDisabled is the
// issue #458 cause-1 regression. The clearing used to sit behind the
// !cfg.AutoUpdate early return, so turning auto_update off after a failure —
// often *because* it failed — stranded the record forever.
func TestAutomaticUpdateCheckClearsStaleAttemptWithAutoUpdateDisabled(t *testing.T) {
	_ = os.Unsetenv("NO_UPDATE_CHECK")
	statePath := seedFailedAttempt(t, "v1.1.0")

	// Running version already satisfies the target, so the check finds no
	// newer release (ok=false) and takes the pre-existing !IsNewer path.
	source := &staticReleaseSource{latest: "v1.1.0"}
	checker := updatepkg.NewChecker(source, statePath)
	cfg := config.Default()
	cfg.AutoUpdate = false
	runner := &recordingUpdateRunner{}

	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "v1.1.0", checker, runner, statePath, "linux")

	if runner.calls != 0 {
		t.Fatalf("update runner invoked %d times with auto_update off, want 0", runner.calls)
	}
	if attempt, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath); ok {
		t.Fatalf("attempt = %+v, want cleared even with auto_update off", attempt)
	}
}

// TestClearStaleAutomaticUpdateAttemptOnlyClearsFailures pins the helper's
// contract: it retires *failure* records, so a recorded success is left alone
// even when the predicate would call it stale. Nothing renders a success
// record today, but the record is the only evidence an unattended install ran
// and clearing it is not this code path's job.
func TestClearStaleAutomaticUpdateAttemptOnlyClearsFailures(t *testing.T) {
	statePath := filepath.Join(t.TempDir(), "update-check.json")
	attemptedAt := time.Date(2026, 7, 28, 17, 46, 2, 0, time.UTC)
	if err := updatepkg.RecordAutomaticUpdateAttempt(statePath, "0.1.3", attemptedAt, nil); err != nil {
		t.Fatal(err)
	}
	before, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath)
	if !ok || before.Error != "" {
		t.Fatalf("harness broken: seeded attempt = (%+v, %t), want a success record", before, ok)
	}

	called := false
	clearStaleAutomaticUpdateAttempt(statePath, func(updatepkg.AutomaticUpdateAttempt) bool {
		called = true
		return true
	})

	if called {
		t.Fatal("staleness predicate consulted for a success record")
	}
	after, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath)
	if !ok || after.Target != before.Target {
		t.Fatalf("attempt = (%+v, %t), want the success record for 0.1.3 preserved", after, ok)
	}

	// A missing state file must be a silent no-op, not a panic or an error:
	// clearing runs on the daemon-startup path.
	clearStaleAutomaticUpdateAttempt(filepath.Join(t.TempDir(), "absent.json"), func(updatepkg.AutomaticUpdateAttempt) bool {
		t.Fatal("staleness predicate consulted with no state file")
		return true
	})
}

// TestAutomaticUpdateCheckKeepsAttemptWhenUpdateCheckDisabled pins the
// opt-out: no network call and no state mutation when the user said no.
func TestAutomaticUpdateCheckKeepsAttemptWhenUpdateCheckDisabled(t *testing.T) {
	_ = os.Unsetenv("NO_UPDATE_CHECK")
	statePath := seedFailedAttempt(t, "1.1.0")

	source := &staticReleaseSource{latest: "0.1.3"}
	checker := updatepkg.NewChecker(source, statePath)
	cfg := config.Default()
	cfg.UpdateCheck = false
	cfg.AutoUpdate = false

	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", checker, &recordingUpdateRunner{}, statePath, "linux")

	if source.calls != 0 {
		t.Fatalf("release source called %d times with update_check off, want 0", source.calls)
	}
	if _, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath); !ok {
		t.Fatal("attempt cleared with update_check off; clearing must not act on state it never checked")
	}

	// The real Checker also honours the flag internally, so the gate above
	// would look enforced even if runAutomaticUpdate dropped it. This stub
	// answers regardless, pinning the gate at this level too.
	disregarding := &flagIgnoringChecker{latest: "0.1.3"}
	stubState := seedFailedAttempt(t, "1.1.0")
	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", disregarding, &recordingUpdateRunner{}, stubState, "linux")
	if disregarding.calls != 0 {
		t.Fatalf("checker called %d times with update_check off, want 0", disregarding.calls)
	}
	if _, ok := updatepkg.ReadAutomaticUpdateAttempt(stubState); !ok {
		t.Fatal("attempt cleared with update_check off via a checker that ignores the flag")
	}

	t.Setenv("NO_UPDATE_CHECK", "1")
	cfg.UpdateCheck = true
	envState := seedFailedAttempt(t, "1.1.0")
	envSource := &staticReleaseSource{latest: "0.1.3"}
	envChecker := updatepkg.NewChecker(envSource, envState)
	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", envChecker, &recordingUpdateRunner{}, envState, "linux")
	if envSource.calls != 0 {
		t.Fatalf("release source called %d times under NO_UPDATE_CHECK, want 0", envSource.calls)
	}
	if _, ok := updatepkg.ReadAutomaticUpdateAttempt(envState); !ok {
		t.Fatal("attempt cleared under NO_UPDATE_CHECK")
	}
}

// TestAutomaticUpdateCheckClearsBogusTargetWhenNoNewerReleaseExists is the
// state the issue #458 reporter's machine is actually in: the bogus target
// "1.1.0" is recorded and the latest real release is the version already
// running. Checker.Check reports no result at all in that case, so a rule
// written against the check's own result never runs — the staleness rule has
// to fall back to the latest version the cache already holds.
func TestAutomaticUpdateCheckClearsBogusTargetWhenNoNewerReleaseExists(t *testing.T) {
	_ = os.Unsetenv("NO_UPDATE_CHECK")
	statePath := seedFailedAttempt(t, "1.1.0")

	source := &staticReleaseSource{latest: "0.1.2"} // latest == running version
	checker := updatepkg.NewChecker(source, statePath)
	cfg := config.Default()
	cfg.AutoUpdate = false

	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", checker, &recordingUpdateRunner{}, statePath, "linux")

	if source.calls == 0 {
		t.Fatal("harness broken: release source was never consulted")
	}
	if attempt, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath); ok {
		t.Fatalf("attempt = %+v, want the bogus 1.1.0 record cleared", attempt)
	}
}

// TestAutomaticUpdateCheckKeepsAttemptWhenLatestIsUnknown pins the
// conservative half of the fallback: with no successful check on file there is
// no evidence about what the source offers, so an offline daemon must leave a
// still-newer target alone rather than guess it away.
func TestAutomaticUpdateCheckKeepsAttemptWhenLatestIsUnknown(t *testing.T) {
	_ = os.Unsetenv("NO_UPDATE_CHECK")
	statePath := seedFailedAttempt(t, "1.1.0")
	if got := updatepkg.LastKnownLatest(statePath); got != "" {
		t.Fatalf("harness broken: LastKnownLatest = %q, want empty", got)
	}

	checker := updatepkg.NewChecker(&failingReleaseSource{}, statePath)
	cfg := config.Default()
	cfg.AutoUpdate = false

	runAutomaticUpdateWithStatePathForPlatform(context.Background(), cfg, "0.1.2", checker, &recordingUpdateRunner{}, statePath, "linux")

	if _, ok := updatepkg.ReadAutomaticUpdateAttempt(statePath); !ok {
		t.Fatal("attempt cleared with no known latest release; an unreachable source is not evidence the target is gone")
	}
}
